use std::collections::BTreeMap;

/// Parses and renders the portable `KEY=value` file format used by Docker
/// `--env-file`, Docker Compose `env_file`, and the local-secrets HTTP API.
///
/// Values are literal text after the first `=` on a line. Blank lines and
/// whole-line `#` comments are allowed; inline comments, shell expansion, and
/// quote removal are intentionally not interpreted.
pub fn parse(contents: &str) -> Result<BTreeMap<String, String>, Vec<String>> {
    let mut variables = BTreeMap::new();
    let mut errors = Vec::new();

    for record in records(contents, &mut errors) {
        variables.insert(record.name.to_string(), record.value.to_string());
    }

    if errors.is_empty() {
        Ok(variables)
    } else {
        Err(errors)
    }
}

/// Returns the env-file representation served to tools such as Docker.
///
/// Comments and blank lines are useful in the editable backing file, but they
/// are not secrets and should not be sent to consumers. The original order and
/// literal values are otherwise preserved.
pub fn to_served_env_file(contents: &str) -> Result<String, Vec<String>> {
    let mut errors = Vec::new();
    let mut served = String::new();

    for record in records(contents, &mut errors) {
        served.push_str(record.name);
        served.push('=');
        served.push_str(record.value);
        served.push('\n');
    }

    if errors.is_empty() {
        Ok(served)
    } else {
        Err(errors)
    }
}

pub fn to_shell_exports(variables: &BTreeMap<String, String>) -> String {
    let mut script = String::from(
        "# Generated by local-secrets. Source this in a trusted POSIX-compatible shell.\n",
    );

    for (name, value) in variables {
        script.push_str("export ");
        script.push_str(name);
        script.push('=');
        script.push_str(&shell_quote(value));
        script.push('\n');
    }

    script
}

pub fn to_fish_exports(variables: &BTreeMap<String, String>) -> String {
    let mut script = String::from("# Generated by local-secrets. Source this in fish.\n");

    for (name, value) in variables {
        script.push_str("set -gx ");
        script.push_str(name);
        script.push(' ');
        script.push_str(&fish_quote(value));
        script.push('\n');
    }

    script
}

/// Returns a display-safe env-file view that preserves keys and local notes but
/// hides non-empty values behind a fixed mask.
///
/// The editable source remains on disk unchanged; this view exists only to
/// reduce accidental disclosure in the browser when the UI is locked.
pub fn obfuscate_values(contents: &str) -> String {
    let mut obfuscated = String::with_capacity(contents.len());

    for segment in contents.split_inclusive('\n') {
        let (line, ending) = segment
            .strip_suffix("\r\n")
            .map(|line| (line, "\r\n"))
            .or_else(|| segment.strip_suffix('\n').map(|line| (line, "\n")))
            .unwrap_or((segment, ""));

        push_obfuscated_line(line, &mut obfuscated);
        obfuscated.push_str(ending);
    }

    obfuscated
}

const OBFUSCATED_VALUE: &str = "••••••••";

struct EnvRecord<'a> {
    name: &'a str,
    value: &'a str,
}

fn records<'a>(contents: &'a str, errors: &mut Vec<String>) -> Vec<EnvRecord<'a>> {
    let mut records = Vec::new();

    for (index, raw_line) in contents.lines().enumerate() {
        let line_number = index + 1;
        let line = raw_line.strip_suffix('\r').unwrap_or(raw_line);
        let trimmed = line.trim_start();

        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        let Some((name, value)) = line.split_once('=') else {
            errors.push(format!(
                "line {line_number}: expected NAME=value with an `=` separator"
            ));
            continue;
        };

        if !is_valid_env_name(name) {
            errors.push(format!(
                "line {line_number}: `{name}` is not a valid environment variable name"
            ));
            continue;
        }

        records.push(EnvRecord { name, value });
    }

    records
}

pub fn is_valid_env_name(name: &str) -> bool {
    let mut chars = name.chars();

    let Some(first) = chars.next() else {
        return false;
    };

    if !(first == '_' || first.is_ascii_alphabetic()) {
        return false;
    }

    chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
}

fn push_obfuscated_line(line: &str, output: &mut String) {
    let trimmed = line.trim_start();

    if trimmed.is_empty() || trimmed.starts_with('#') {
        output.push_str(line);
        return;
    }

    let Some((name, value)) = line.split_once('=') else {
        output.push_str(line);
        return;
    };

    output.push_str(name);
    output.push('=');
    if !value.is_empty() {
        output.push_str(OBFUSCATED_VALUE);
    }
}

fn shell_quote(value: &str) -> String {
    let mut quoted = String::from("'");

    for ch in value.chars() {
        if ch == '\'' {
            quoted.push_str("'\\''");
        } else {
            quoted.push(ch);
        }
    }

    quoted.push('\'');
    quoted
}

fn fish_quote(value: &str) -> String {
    let mut quoted = String::from("'");

    for ch in value.chars() {
        if ch == '\'' {
            quoted.push_str("\\'");
        } else {
            quoted.push(ch);
        }
    }

    quoted.push('\'');
    quoted
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_literal_env_file() {
        let parsed = parse(
            r#"
# local development
DATABASE_URL=postgres://localhost/app?sslmode=disable
TOKEN=abc=def#not-a-comment
EMPTY=
"#,
        )
        .unwrap();

        assert_eq!(
            parsed["DATABASE_URL"],
            "postgres://localhost/app?sslmode=disable"
        );
        assert_eq!(parsed["TOKEN"], "abc=def#not-a-comment");
        assert_eq!(parsed["EMPTY"], "");
    }

    #[test]
    fn serves_env_file_without_comments_or_blank_lines() {
        let served = to_served_env_file(
            r#"
# This comment stays local.
DATABASE_URL=postgres://localhost/app

# Another local-only note.
TOKEN=abc#not-a-comment
"#,
        )
        .unwrap();

        assert_eq!(
            served,
            "DATABASE_URL=postgres://localhost/app\nTOKEN=abc#not-a-comment\n"
        );
    }

    #[test]
    fn rejects_non_portable_names() {
        let errors = parse("1BAD=value\nHAS SPACE=value\nMISSING_EQUALS\n").unwrap_err();

        assert_eq!(errors.len(), 3);
        assert!(errors[0].contains("1BAD"));
        assert!(errors[1].contains("HAS SPACE"));
        assert!(errors[2].contains("separator"));
    }

    #[test]
    fn obfuscates_values_without_revealing_lengths() {
        let obfuscated = obfuscate_values(
            "# local note\nDATABASE_URL=postgres://localhost/app\r\nEMPTY=\nMISSING_EQUALS\nTOKEN=short\n",
        );

        assert_eq!(
            obfuscated,
            "# local note\nDATABASE_URL=••••••••\r\nEMPTY=\nMISSING_EQUALS\nTOKEN=••••••••\n"
        );
    }

    #[test]
    fn shell_exports_are_quoted() {
        let mut variables = BTreeMap::new();
        variables.insert("A".to_string(), "plain".to_string());
        variables.insert("B".to_string(), "has spaces and $dollars".to_string());
        variables.insert("C".to_string(), "it's ok".to_string());

        let script = to_shell_exports(&variables);

        assert!(script.contains("export A='plain'"));
        assert!(script.contains("export B='has spaces and $dollars'"));
        assert!(script.contains("export C='it'\\''s ok'"));
    }

    #[test]
    fn fish_exports_are_quoted() {
        let mut variables = BTreeMap::new();
        variables.insert("A".to_string(), "plain".to_string());
        variables.insert("B".to_string(), "has spaces and $dollars".to_string());
        variables.insert("C".to_string(), "it's ok".to_string());

        let script = to_fish_exports(&variables);

        assert!(script.contains("set -gx A 'plain'"));
        assert!(script.contains("set -gx B 'has spaces and $dollars'"));
        assert!(script.contains("set -gx C 'it\\'s ok'"));
    }
}
